"""Trading signal data models."""
from datetime import datetime
from decimal import Decimal
from pydantic import BaseModel
from quant.utils.types import Direction, TimeFrame, SignalType, Underlying
from quant.models.contracts import GreeksSnapshot, MultiLegPosition

class SignalPayload(BaseModel):
    """A trading signal generated by a strategy."""
    timestamp: datetime
    strategy_name: str
    strategy_id: str
    underlying: Underlying
    timeframe: TimeFrame
    direction: Direction
    position: MultiLegPosition
    max_profit: Decimal
    max_loss: Decimal
    risk_reward_ratio: float
    confidence_score: float
    greeks: GreeksSnapshot
    signal_type: SignalType
    notes: str = ""
