name: Sync Secrets from Source Repo

on:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: jpoehnelt/secrets-sync-action@v1.10.0
        with:
          secrets: |
            FYERS_APP_ID
            FYERS_SECRET_KEY
            FYERS_PIN
            TELEGRAM_BOT_TOKEN
          repositories: |
            chintanmehta21/PivotPoint
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        env:
          FYERS_APP_ID: ${{ secrets.FYERS_APP_ID }}
          FYERS_SECRET_KEY: ${{ secrets.FYERS_SECRET_KEY }}
          FYERS_PIN: ${{ secrets.FYERS_PIN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
